version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    networks:
      - orion
    environment:
      - MYSQL_ROOT_PASSWORD=orion
      - MYSQL_DATABASE=orion

  server:
    restart: always
    networks:
      - orion
      - traefik
    build:
      context: orion-server
      args:
        sha: fedb85c8b2980bfc4dea7bf93ca17e059f63b1c1
        database_host: db
        database_port: 3306
        database_name: orion
        database_user: root
        database_password: orion
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.rule=Host:${SERVER_HOST};PathPrefix:/api"
      - "traefik.frontend.auth.basic=${BASIC_AUTH}"

  web:
    restart: always
    build:
      context: orion-web
      args:
        sha: 8c18dce19a2199c4c53e1145881d362a05018cd5
        mapbox_api_token: ${MAPBOX_API_TOKEN}
        orion_server_url: https://${SERVER_HOST}
    depends_on:
      - server
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.port=3001"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.rule=Host:${HOST}"
      - "traefik.frontend.auth.basic=${BASIC_AUTH}"

networks:
  orion: {}
  traefik:
    external: true